algorithm:
  _target_: algorithms.bandits.implementations.BanditAgent.BanditAgent
  params:
    action_value_strategy:
      _target_: algorithms.bandits.implementations.action_value.ERWAverageSampling.ERWAverageSampling
      alpha: 0.1
    exploration_strategy:
      _target_: algorithms.bandits.implementations.exploration.EpsilonGreedy.EpsilonGreedy
      epsilon: 0.1
    metrics:
    - step
    - action
    - reward
    - total_reward
    - average_reward
    - optimal_chosen_counter
    - optimal_chosen_percentage
environment:
  _target_: environments.custom_envs.BanditEnvs.KArmEnvironment.KArmEnvironment
  params:
    number_of_arms: 10
    max_steps: 10000
    drift_strategy:
      _target_: environments.custom_envs.BanditEnvs.drift.GaussianDrift.GaussianDrift
      mean: 0
      variance: 0.01
    reward_strategy:
      _target_: environments.custom_envs.BanditEnvs.reward.GaussianReward.GaussianReward
      variance: 1
run:
  name: Ex_2.5
  episodes: 1
  agent_seed: 20
  env_seed: 35
repro_folder_name: Exercise_2.5
