_target_: algorithms.bandits.implementations.BanditAgent.BanditAgent
params:
  action_value_strategy:
    _target_: algorithms.bandits.implementations.action_value.AverageSampling.AverageSampling
  exploration_strategy:
    _target_: algorithms.bandits.implementations.exploration.EpsilonGreedy.EpsilonGreedy
    epsilon: 0.1
  metrics:
  - step
  - action
  - reward
  - total_reward
  - average_reward
  - optimal_chosen_percentage